### ISSUE TITLE
Use warn instead of printing the command

### ISSUE THREAD

**Issue by toadative** [Mullets-Gavin/Deliver#2]
It is difficult to see when one command ends and another starts. I think you should consider using warn for the "> --command" bit instead.

**Comment by toadative** [comment]
Nevermind, that part actually comes from Studio. I wonder if there is another way to make each command stand out?

**Comment by Mullets-Gavin** [comment]
This was a question I had tried to answer, but ultimately went with the idea of windows terminal, since it behaves the same way:

![image](https://user-images.githubusercontent.com/38087728/104091178-ce2bcf80-5249-11eb-8709-b6baa15d72c4.png)

I originally attempted providing whitespace/a spam of characters but both of those options turned out to be terrible bloat that made it worse. I recommend disabling Roblox's output fluff for the best *visual* appearance:

![image](https://user-images.githubusercontent.com/38087728/104091225-07643f80-524a-11eb-85f6-a436c15b2606.png)

I'm closing this issue and marking it as "wont fix" but if there's a possible solution, I'll look into implementing it.
